# vanna_lgx/core/state.py
from typing import TypedDict, Any, List, Dict
import pandas as pd



class GraphState(TypedDict):
    """
    Represents the state of our graph.
    
    Attributes:
        question: The user's input question.
        db_schema: The full DDL of the database.
        sql_query: The SQL query generated by the LLM.
        result: The result of executing the SQL query.
        summary: The natural language summary of the result.
        error: A string to hold any error message that occurs.
    """
    question: str
    db_schema: str
    retrieved_examples: List[Dict[str, str]] # <-- NEW FIELD
    sql_query: str
    result: pd.DataFrame | None
    summary: str
    error: str | None